### ISSUE TITLE
文件编码问题

### ISSUE THREAD

**Issue by HowcanoeWang** [copperay/ZRM_Aux-code#2]
默认的文件编码是GBK，但是手心收入法mac版需要导入Unicode编码格式(UTF-8)

<img width="260" alt="image" src="https://user-images.githubusercontent.com/19968935/201249742-56f49f5c-4390-4ae2-a76c-0eaf52557a0f.png">

**Comment by HowcanoeWang** [comment]
转成UTF-8还是导入失败，可能是客户端有别的格式要求，但找不到官方文档

**Comment by tstts** [comment]
我尝试了转utf-16可以导入。

**Comment by HowcanoeWang** [comment]
> 我尝试了转utf-16可以导入。

确实，用vscode改成`utf-16 LE`成功导入了，`utf-16 BE`依然失败

**Comment by edte** [comment]
iconv -c -f GBK -t UTF-16LE  ZRM_Aux-code_4.3.txt > ZRM_Aux-code_4.4.txt
